# Generated by Django 3.2 on 2022-12-23 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_user_confirmation_code'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='unique_username_email',
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='О себе'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='admin', max_length=150, unique=True, verbose_name='Имя пользователя'),
            preserve_default=False,
        ),
    ]
